### ISSUE TITLE
Trouble with Msg script

### ISSUE THREAD

**Issue by cvelele** [madprops/Msg#4] opened 2017-09-18 19:32 UTC
I have trouble with Msg script to do something like this.

If it is simple form like this:

```
<form method="post" action="index.html" onsubmit="return formCheck(this) && remind() && pause ()">
	<input type="text" name="name" />
	<input type="text" name="email" />
	<input type="submit" value="Submit" />
</form>
<span onclick='remind();'>Run This Demo</span>
```

I have first function to validate email, if ok show message remind, pause for 3 sec and proceed with submitting.

```
<script>
function formCheck()
...
</script>
```

```
<script>
function remind(html)
...
</script>
```

```
<script>
function pause() {
timer = setTimeout("endpause()",3000); // 3 secs
return false;
}

function endpause() { 
document.forms[0].submit(); 
return false; 
}
</script>
```

What happens is that function validate works ok, skips Msg script (not showing at all), pause 3 sec and than submit.
Msg script works ok when clicked, independently on next line (span).

Any suggestion?

**Comment by madprops** [comment] 2017-09-18 22:06
Hi, can you provide the full code of those functions including the Msg script?

**Comment by cvelele** [comment] 2017-09-19 10:16
Here it is:

function formCheck

```
<script language="JavaScript">
<!--
/***********************************************
* Required field(s) validation v1.10- By NavSurf
* Visit Nav Surf at http://navsurf.com
* Visit http://www.dynamicdrive.com/ for full source code
***********************************************/

function formCheck(formobj){
	// Enter name of mandatory fields
	var fieldRequired = Array("email","name");
	// Enter field description to appear in the dialog box
	var fieldDescription = Array("email","name");
	// dialog message
	var alertMsg = "Fill in:\n";
	
	var l_Msg = alertMsg.length;
	
	for (var i = 0; i < fieldRequired.length; i++){
		var obj = formobj.elements[fieldRequired[i]];
		if (obj){
			switch(obj.type){
			case "select-one":
				if (obj.selectedIndex == -1 || obj.options[obj.selectedIndex].text == ""){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			case "select-multiple":
				if (obj.selectedIndex == -1){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			case "text":
			case "textarea":
				if (obj.value == "" || obj.value == null){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			default:
			}
			if (obj.type == undefined){
				var blnchecked = false;
				for (var j = 0; j < obj.length; j++){
					if (obj[j].checked){
						blnchecked = true;
					}
				}
				if (!blnchecked){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
			}
		}
	}

	if (alertMsg.length == l_Msg){
		return true;

	}else{
		alert(alertMsg);
		return false;
	}

}
// -->
</script>
```

function remind

```
<script>
function remind(html)
	{
		var msg = Msg({
		class: "black",
		content_class: "snackbar",
		position: "bottom",
		edge_padding_y: 0,
		window_min_width: "100%",
		window_x: "none",
		enable_overlay: false,
		autoclose: true,
		autoclose_delay: 2000,
		close_on_show: true,
		show_effect: "slide_up",
		show_effect_duration: 350,
		close_effect: "slide_down",
		close_effect_duration: 350,        
		sideStack: "none",
		zStack_level: 1,
		lock: false,
	});
		msg.show("Thank you.",["Snackbars", html]);
}
</script>
```

I am not so skilled in programming.

I have two ideas about this problem.
Noticed in your example this:

```
var msg_delay = Msg(
{
    temp_disable_close:true,
    temp_disable_close_delay:5000,
    after_show: function(instance)
    {
        setTimeout(function()
        {
            instance.set("This had a 5 second delay before you could close it. Made to avoid closing the window by accident by misclicking. Default for this option is 1 second.");
        }, 4500);
    }
});
```
Somehow to use this setTimeout for my problem.

Second idea to show confirmation after page load:

`<form method="post" action="index.html">`

with somethig like:

`<form method="post" action="index.html?remind()">`

Thx

**Comment by madprops** [comment] 2017-09-19 21:13
Ok, first of all I don't see remind() being called in the validation function. You will need to call it somewhere after it validates correctly. For instance something like:

```
var valid = formCheck(formObj)

if(valid)
{
    remind("Thank You.")
}
```

Or you can start remind() right before formCheck returns true

```
	if (alertMsg.length == l_Msg){
                remind("Thank You.")
		return true;

	}else{
		alert(alertMsg);
		return false;
	}
```

Now, I fixed the msg instancing.

```
function remind(html)
{
	var msg = Msg
	({
		// Other options up here
		// This option runs as soon as msg fully closes (slides all the way down)
		after_close: function()
		{
			document.forms[0].submit();
		}
	})

	// Notice how I fixed this. 
	msg.show(html);
}
```

To use remind() you have to pass it a string. Like remind("Thank  You.")

Notice how I added an after_close option. This will run right after it closes. You have an autoclose_delay of 2000, which means it will start closing after 2 seconds. When it fully closes it will run the after_close function, which submits the form.

Now if you want to show a message on page load, it's a bit more complicated, but you have various options.

a) Make the new page url have a special GET argument like  index.html?remind  -- Then check on load if that argument is present and fire the remind function. 

b) Use localStorage, or cookies to save a value that you check on each page load. If the value is present, do something, then remove the value.

I know this might be a little complicated, but I hope this can help you a bit more. If you have more questions I'd be glad to answer them.

**Comment by cvelele** [comment] 2017-09-20 17:35
Thank you for your patience.

Great fix for remind(html) with after_close option. But I am still doing something wrong.
Here is simplify example with all code:

```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
<script src="js/msg.js"></script>
</head>

<body>
<script language="JavaScript">

<!--
/***********************************************
* Required field(s) validation v1.10- By NavSurf
* Visit Nav Surf at http://navsurf.com
* Visit http://www.dynamicdrive.com/ for full source code
***********************************************/

function formCheck(formobj){
	// Enter name of mandatory fields
	var fieldRequired = Array("email");
	// Enter field description to appear in the dialog box
	var fieldDescription = Array("email");
	// dialog message
	var alertMsg = "Fill this:\n";
	
	var l_Msg = alertMsg.length;
		
	for (var i = 0; i < fieldRequired.length; i++){
		var obj = formobj.elements[fieldRequired[i]];
		if (obj){
			switch(obj.type){
			case "select-one":
				if (obj.selectedIndex == -1 || obj.options[obj.selectedIndex].text == ""){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			case "select-multiple":
				if (obj.selectedIndex == -1){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			case "text":
			case "textarea":
				if (obj.value == "" || obj.value == null){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
				break;
			default:
			}
			if (obj.type == undefined){
				var blnchecked = false;
				for (var j = 0; j < obj.length; j++){
					if (obj[j].checked){
						blnchecked = true;
					}
				}
				if (!blnchecked){
					alertMsg += " - " + fieldDescription[i] + "\n";
				}
			}
		}
	}

	if (alertMsg.length == l_Msg){
		remind("Thank You.")
		return true;

	}else{
		alert(alertMsg);
		return false;
	}

}
// -->
</script>
<script>
function remind(html) {
		var msg = Msg
		({
			class: "black",
			content_class: "snackbar",
			position: "bottom",
			edge_padding_y: 0,
			window_min_width: "100%",
			window_x: "none",
			enable_overlay: false,
			autoclose: true,
			autoclose_delay: 2000,
			close_on_show: true,
			show_effect: "slide_up",
			show_effect_duration: 350,
			close_effect: "slide_down",
			close_effect_duration: 350,        
			sideStack: "none",
			zStack_level: 1,
			lock: false,
			after_close: function()
				{
					document.forms[0].submit();
				}
		})
		msg.show(html);
}
</script>
<p>
<span onclick='remind("Thank You.");'>Run This Demo</span>
<p>
<form method="post" action="index.html" onsubmit="return formCheck(this)">
	<p>Name:</p>
    <input type="text" name="name" />
	<p>email:</p>
    <input type="text" name="email" />
	<input type="submit" value="Submit" />
</form>

</body>
</html>
```

I implemented after_close: function(), add remind() right before formCheck returns true and what I get is this.

When clicked on Run This Demo , snackbar shoes and closes after 2sec and then get redirected to index.html. Works. Great.
But when fill form with name and email and click submit instantly get redirected to index.html. No snackbar, no pause.

Where is the error?

**Comment by madprops** [comment] 2017-09-20 19:27
Ok found the problem. The problem is that as soon as formCheck returns true, the form will be submitted.

I tried this at the end of formCheck, and it works:

```
	if (alertMsg.length == l_Msg){
		remind("Thank You.")

	}else{
		alert(alertMsg);
	}

	return false
```

Basically, if it's ready to go, it fires up msg. If it has errors, it shows the alert with the errors. And it always returns false, so it isn't submitted automatically. So if it's correct, it fires up msg, returns false so it wont be submitted immediately, then msg's after_close submits it later.

**Comment by madprops** [comment] 2017-09-20 19:37
Also you might want to say "Thank You (Submitting)" so someone doesn't close the tab immediately before it submits. Ideally you could submit the form immediately on the background using ajax, but that's more complicated, but something that's good to know.

**Comment by cvelele** [comment] 2017-09-21 11:24
Yes.
Man you rock.

Thank you:)

**Closed as completed** 2017-09-30 04:07 UTC
